# example:
# 读取app下的name：viper.GetString("app.name")
# 读取int类型：    viper.GetInt("xxx.xxx")
# 详情见：https://github.com/spf13/viper

app:
  name: dousheng
  secret: going小分队
  # stroage_host is used for play_url.
  # for example, if stroage_host is 'example.com:80'.
  # server will tell client to get video from http://example.com:80/static/${video}
  storage: "host or host:port" 

db:
  driver: mysql
  host: example.com
  port: 3306
  user: demo
  pass: secret
  database: dousheng
  loglevel: 1 # 1,2,3,4 对应 slient error warn info
